### ISSUE TITLE
Kodi Python 3.7

### ISSUE THREAD

**Issue by robweber** [micahg/script.module.dropbox#13]
Just wanted to point this out for the migration to Python 3 for Kodi v19. 

Currently the version of Python 3 being bundled with Kodi is [3.7.3](https://github.com/xbmc/xbmc/blob/master/tools/depends/native/python3/Makefile) per the master repo. When testing the Dropbox addon on a Python 3 build I noticed errors getting the addon to import. I traced these back to the Dropbox Python SDK repo, specifically[ this issue](https://github.com/dropbox/dropbox-sdk-python/issues/145). It looks like version [9.0.0](https://github.com/dropbox/dropbox-sdk-python/tree/v9.0.0) of the SDK is the first one that will work on Python 3.7.  Looks like the newest tagged version is[ 9.4.0](https://github.com/dropbox/dropbox-sdk-python/tree/v9.4.0). 

While ok for now the 8.4.2 version in the Kodi repo won't work with Python 3 as bundled with Kodi in the future. No rush in getting this updated (and not sure what v8 vs v9 will break) but at some point this will need to get updated to stay compatible.

**Comment by micahg** [comment]
Thanks @robweber - I'll stick this on my todo list for some time in the future.

**Comment by VastGsm** [comment]
Any updates on this
Kodi 19x now uses Python 3x for all addons I believe

**Comment by robweber** [comment]
This probably should have been closed with the mentioned PR (#14). The current version is 9.4.0, which is Python 3 compatible. While probably not the newest version of the Dropbox API it should be working in Kodi Matrix+
