### ISSUE TITLE
Python syntax error on Android and OSX

### ISSUE THREAD

**Issue by SchapplM** [micahg/script.module.dropbox#3]
It seems, that there is an error when trying to import the dropbox plugin in other addons.
See these error reports (python error stacks) pointing to rest.py, L415, C43:
http://forum.kodi.tv/showthread.php?tid=164652&pid=2347138#pid2347138
http://forum.kodi.tv/showthread.php?tid=164652&pid=2351646#pid2351646

Since a syntax error is reported and this does not occur on other systems, there could be an error with the Python version (but just guessing). (perhaps other python version in addon.xml has to be required)
The error occured on Android and OSX. I successfully tested the addon on Ubuntu and Windows.

**Comment by micahg** [comment]
OK, I'll try to investigate further... I also only tested on Ubuntu and Windows...  I'll grab the latest on my Nexus player and take a look when I'm able.
